"""Generated by scripts/generate-design-tokens.mjs. Do not edit."""

EXPORT_COLORS = {
  "background": "#FFFFFF",
  "textPrimary": "#1F2933",
  "textSecondary": "#5F6B66",
  "grid": "#DCE2DE",
  "gridStrong": "#AAB5AF",
  "beadOutline": "#AAB5AF"
}
