export {
  PIXELANIM_GRID_COLUMNS,
  PIXELANIM_GRID_RATIO,
  PIXELANIM_GRID_ROWS,
  PIXELANIM_HORIZONTAL_BOUNDARY_COUNT,
  PIXELANIM_VERTICAL_BOUNDARY_COUNT,
} from '../grid-selection/constants';

export const MAX_ANALYSIS_LONG_EDGE = 1200;
export const MIN_ANALYSIS_CELL_SIZE = 4;
export const AXIS_CANDIDATE_LIMIT = 72;
export const MAX_BOUNDARY_SEARCH_PIXELS = 28;
