export const MAX_ANALYSIS_LONG_EDGE = 1200;
export const MIN_ANALYSIS_CELL_SIZE = 4;
export const MIN_DETECTED_GRID_SEGMENTS = 2;
export const AXIS_CANDIDATE_LIMIT = 28;
export const AXIS_STEP_CANDIDATE_LIMIT = 32;
export const MAX_BOUNDARY_SEARCH_PIXELS = 28;
