export const PIXELANIM_GRID_COLUMNS = 34;
export const PIXELANIM_GRID_ROWS = 27;
export const PIXELANIM_VERTICAL_BOUNDARY_COUNT = PIXELANIM_GRID_COLUMNS + 1;
export const PIXELANIM_HORIZONTAL_BOUNDARY_COUNT = PIXELANIM_GRID_ROWS + 1;
export const PIXELANIM_GRID_RATIO = PIXELANIM_GRID_COLUMNS / PIXELANIM_GRID_ROWS;

export const MAX_ANALYSIS_LONG_EDGE = 1200;
export const MIN_ANALYSIS_CELL_SIZE = 4;
export const AXIS_CANDIDATE_LIMIT = 72;
export const MAX_BOUNDARY_SEARCH_PIXELS = 28;
