// Generated by scripts/generate-brand-config.mjs. Do not edit.
export const brandConfig = {
  "productName": "6个造物社",
  "englishName": "Bean Pattern Studio",
  "shortName": "造物社",
  "description": "简单、准确的拼豆图纸设计工具",
  "themeId": "mint-studio"
} as const;
